# Implement docker healthcheck and stopsignal using dockerfile
# Containerize a simple flask deploy
#
# install ubuntu 18.04
#??
# update OS
#??
#??
#??
#??
# set environment variable LC_ALL to C.UTF-8
#??
# set environment variable LANG to C.UTF-8
#??
# deploy app
#??
# set working directory to app
#??
# install dependencies
#??
# start taskmanager
#??
